@startuml
interface Shape {
    setFill(fill:string) : void
    getFill() : string
    setStroke(stroke:string) : void
    getStroke() : string
    setStrokeWidth(strokewidth:string) : void
    getStrokeWidth() : string
    getShapeAttribute() : string
}
@enduml
